version: '3.8'
services:
  dyma-postgresql:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data